image: node:latest

cache:
  paths:
    - node_modules/
    - .yarn

pages:
  script:
    - yarn global add node-gyp
    - yarn
    - export NODE_ENV='production'
    - yarn export
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - master
